### ISSUE TITLE
can't be installed

### ISSUE THREAD

**Issue by aljosa** [google/VoltAir#1]
i'm putting this here since i can't write a review on play store.
best guess, this can only be installed on devices in US.

this game/demo is a complete failure and the worst thing is that it's all probably because of a stupid mistake in deployment/launch.

i have a nexus 5/kitkat (and 2 other android devices) and i can't install this game from play store:
"This app is incompatible with all of your devices."

looking at video it looks awesome and especially interesting since it uses Qt.

**Comment by bwrichte** [comment]
Hi Aljosa,

Unfortunately, as only a demo and framework exploration, we were unable to localize VoltAir into any other languages besides English (US), and, as a result, needed to restrict the Play Store release to the US for policy and UX reasons.

However, if you are still interested in playing around with the game, have a look at our [Getting Started page](http://google.github.io/VoltAir/doc/gettingStarted/html/index.html) for downloading, building, and running the VoltAir source code for your Android devices.  I'd be more than happy to answer any questions or help you with any difficult steps in doing so.

Thanks for your interest!

--Bryan R.
