### ISSUE TITLE
QML in design mode not working with QTCreator

### ISSUE THREAD

**Issue by vsidou** [google/VoltAir#6]
Hello everyone,

First nice thanks for this awesome project. 
I have tried top open this project using QTCreator. I followed the wiki on QT installation.
I use QTCreator version 5.4.1.

The project opens fine and i could select my kits with success.
I can edit the QML code also.
But when i try to open the QML in design mode i get the following error in the terminal : 
###### Qt/Tools/QtCreator/share/qtcreator/qmldesigner/statesEditorQmlSources/StatesDelegate.qml:125:9: QML Image: Failed to get image from provider: image://qmldesigner_stateseditor/1-5

and a few more messages like that.

The designer just open a grey page. That is the same for all QML in the project.
I use Ubuntu and don't have windows. I can still try to virtualize one to test but wanted your feedback.

Anyone encountered the same error please ?

Thanks a lot
Siddique

**Comment by marco-piccolino** [comment]
are any files in Voltair meant to be visually edited in Designer at all? from what I know, looking at the code it does not seem to be the case, otherwise you would have files with the .ui.qml extension. Anybody please correct me if I'm wrong.

**Comment by adderly** [comment]
@marco-piccolino  It is not supposed to be editable by the designer.

As far as i know this was written when qt5.2~3 was available so no ui.qml was available at that time. Actually you can edit any .qml file with the designer, the problem to use these components is that some are custom types defined in c++ or use some components defined in c++ (Util functions). Which the designer don't understand.

So @vsidou , if you want to edit those files they have no size defined width and height thats why you get a gray screen. And for things as images and stuff, change the source by hand to the qml default. (qrc or normal_path_to_image).

**Comment by vsidou** [comment]
Hi @adderly and @marco-piccolino,

Thanks for your comments.

I'll dig into the qml code to get a better understanding.
 I just really wanted to make sure it wasn't editable.

Cheers
